const Employee_Data = [
  {
    id: 1,
    firstName: "Arpita",
    lastName: "Garg",
    email: "arpita@gmail.com",
    salary: "70,000",
    date: "1-Jan-2023",
  },
  {
    id: 2,
    firstName: "Arpita",
    lastName: "Gupta",
    email: "arpitagupta@gmail.com",
    salary: "75,000",
    date: "2-Jan-2023",
  },
  {
    id: 3,
    firstName: "Yachika",
    lastName: "Garg",
    email: "yachika@gmail.com",
    salary: "80,000",
    date: "3-Jan-2023",
  },
  {
    id: 4,
    firstName: "Yachika",
    lastName: "Gupta",
    email: "yachikagupta@gmail.com",
    salary: "85,000",
    date: "4-Jan-2023",
  },
  {
    id: 5,
    firstName: "Yachu",
    lastName: "Garg",
    email: "yachu@gmail.com",
    salary: "90,000",
    date: "5-Jan-2023",
  },
  {
    id: 6,
    firstName: "Yachu",
    lastName: "Gupta",
    email: "yachugupta@gmail.com",
    salary: "95,000",
    date: "6-Jan-2023",
  },
  {
    id: 7,
    firstName: "Yacha",
    lastName: "Garg",
    email: "yacha@gmail.com",
    salary: "65,000",
    date: "7-Jan-2023",
  },
  {
    id: 8,
    firstName: "Yacha",
    lastName: "Gupta",
    email: "yachagupta@gmail.com",
    salary: "60,000",
    date: "8-Jan-2023",
  },
  {
    id: 9,
    firstName: "Gola",
    lastName: "Garg",
    email: "gola@gmail.com",
    salary: "55,000",
    date: "9-Jan-2023",
  },
  {
    id: 10,
    firstName: "Venomous",
    lastName: "Gola",
    email: "venomous_gola@gmail.com",
    salary: "50,000",
    date: "10-Jan-2023",
  }
];

export default Employee_Data;
