const Employee_Data = [
  {
    id: 1,
    firstName: "Arpita",
    lastName: "Garg",
    email: "arpita@gmail.com",
    salary: 70000,
    date: "2023-1-1",
  },
  {
    id: 2,
    firstName: "Arpita",
    lastName: "Gupta",
    email: "arpitagupta@gmail.com",
    salary: 75000,
    date: "2023-1-2",
  },
  {
    id: 3,
    firstName: "Yachika",
    lastName: "Garg",
    email: "yachika@gmail.com",
    salary: 80000,
    date: "2023-1-3",
  },
  {
    id: 4,
    firstName: "Yachika",
    lastName: "Gupta",
    email: "yachikagupta@gmail.com",
    salary: 85000,
    date: "2023-1-4",
  },
  {
    id: 5,
    firstName: "Yachu",
    lastName: "Garg",
    email: "yachu@gmail.com",
    salary: 90000,
    date: "2023-1-5",
  },
  {
    id: 6,
    firstName: "Yachu",
    lastName: "Gupta",
    email: "yachugupta@gmail.com",
    salary: 95000,
    date: "2023-1-6",
  },
  {
    id: 7,
    firstName: "Yacha",
    lastName: "Garg",
    email: "yacha@gmail.com",
    salary: 65000,
    date: "2023-1-7",
  },
  {
    id: 8,
    firstName: "Yacha",
    lastName: "Gupta",
    email: "yachagupta@gmail.com",
    salary: 60000,
    date: "2023-1-8",
  },
  {
    id: 9,
    firstName: "Gola",
    lastName: "Garg",
    email: "gola@gmail.com",
    salary: 55000,
    date: "2023-1-9",
  },
  {
    id: 10,
    firstName: "Venomous",
    lastName: "Gola",
    email: "venomous_gola@gmail.com",
    salary: 50000,
    date: "2023-1-10",
  },
];

export default Employee_Data;
